# Form implementation generated from reading ui file 'C:\Users\legal\PycharmProjects\PythonProject\MainApp\UI\UI_FACEID.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 512)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 501, 31))
        self.label_2.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(167, 167, 167);")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 471))
        self.label.setStyleSheet("border: 2px solid rgb(31, 92, 171);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\legal\\PycharmProjects\\PythonProject\\MainApp\\UI\\../UI APP/background5.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.labelCamera = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelCamera.setGeometry(QtCore.QRect(260, 60, 280, 380))
        self.labelCamera.setStyleSheet("border: 0px solid #1f5cab;\n"
"border-radius: 190px;   \n"
"background-color: transparent;")
        self.labelCamera.setObjectName("labelCamera")
        self.label.raise_()
        self.label_2.raise_()
        self.labelCamera.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Please look straight into the webcam</span></p></body></html>"))
        self.labelCamera.setText(_translate("MainWindow", "TextLabel"))
