# Form implementation generated from reading ui file 'C:\Users\legal\PycharmProjects\PythonProject\MainApp\UI\UI_HOME.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 512)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(0, 0, 151, 51))
        self.gridFrame.setStyleSheet("background-color: rgb(30, 33, 40);")
        self.gridFrame.setObjectName("gridFrame")
        self.label = QtWidgets.QLabel(parent=self.gridFrame)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridFrame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_2.setGeometry(QtCore.QRect(0, 50, 151, 371))
        self.gridFrame_2.setStyleSheet("background-color: rgb(47, 53, 58);")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 90, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"    color: white; \n"
"\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    padding: 15px 0px 20px 5px; \n"
"    text-align: center; \n"
"\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"    color: white; \n"
"\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    padding: 15px 0px 20px 5px; \n"
"    text-align: center; \n"
"\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 170, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("\n"
"    color: white; \n"
"\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    padding: 15px 0px 20px 5px; \n"
"    text-align: center; \n"
"\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 210, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("\n"
"    color: white; \n"
"\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none;\n"
"    font-size: 16px;\n"
"    padding: 15px 0px 20px 5px; \n"
"    text-align: center; \n"
"\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridFrame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_3.setGeometry(QtCore.QRect(0, 420, 151, 51))
        self.gridFrame_3.setStyleSheet("background-color: rgb(30, 33, 40);")
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridFrame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_4.setGeometry(QtCore.QRect(150, 0, 651, 51))
        self.gridFrame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridFrame_4.setObjectName("gridFrame_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 10, 56, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(440, 50, 56, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(320, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(250, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_3 = QtWidgets.QLabel(parent=self.gridFrame_4)
        self.label_3.setGeometry(QtCore.QRect(480, 0, 141, 41))
        self.label_3.setStyleSheet("font: 8pt;")
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_3.setObjectName("label_3")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_10.setGeometry(QtCore.QRect(220, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridFrame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_5.setGeometry(QtCore.QRect(150, 50, 651, 421))
        self.gridFrame_5.setStyleSheet("background-color: rgb(227, 244, 245);")
        self.gridFrame_5.setObjectName("gridFrame_5")
        self.HOME = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.HOME.setGeometry(QtCore.QRect(290, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HOME.setFont(font)
        self.HOME.setObjectName("HOME")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.gridFrame_5)
        self.scrollArea.setGeometry(QtCore.QRect(40, 150, 291, 181))
        self.scrollArea.setStyleSheet("background-color: rgb(227, 244, 245);\n"
"border-radius: 10px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 291, 181))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 70, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(110, 190, 68);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 8px;\n"
"text-align: center; ")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(90, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 9pt;\n"
"font-style: italic;")
        self.label_2.setObjectName("label_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.welcome = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.welcome.setGeometry(QtCore.QRect(40, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.welcome.setFont(font)
        self.welcome.setObjectName("welcome")
        self.khichle = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.khichle.setGeometry(QtCore.QRect(40, 110, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.khichle.setFont(font)
        self.khichle.setStyleSheet("font: 9pt;")
        self.khichle.setObjectName("khichle")
        self.frame = QtWidgets.QFrame(parent=self.gridFrame_5)
        self.frame.setGeometry(QtCore.QRect(380, 60, 231, 291))
        self.frame.setStyleSheet("background-color: rgb(31, 92, 171);\n"
"border-radius: 12px;\n"
"    ")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(19, 39, 191, 231))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.increase = QtWidgets.QLabel(parent=self.frame_2)
        self.increase.setGeometry(QtCore.QRect(10, 30, 101, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.increase.setFont(font)
        self.increase.setStyleSheet("color: rgb(31, 92, 171)")
        self.increase.setObjectName("increase")
        self.goal = QtWidgets.QLabel(parent=self.frame_2)
        self.goal.setGeometry(QtCore.QRect(60, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.goal.setFont(font)
        self.goal.setObjectName("goal")
        self.widget = QtWidgets.QWidget(parent=self.frame_2)
        self.widget.setGeometry(QtCore.QRect(20, 69, 151, 131))
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.label_7.setGeometry(QtCore.QRect(150, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 12pt;\n"
"font-weight: bold;\n"
"font-style: italic;\n"
"color: rgb(31, 92, 171);")
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">PowerSight</span></p></body></html>"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Account"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Notification"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Languages"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Help"))
        self.pushButton_5.setText(_translate("MainWindow", "HOME"))
        self.pushButton_6.setText(_translate("MainWindow", "HOME"))
        self.pushButton_7.setText(_translate("MainWindow", "CHATBOT"))
        self.pushButton_9.setText(_translate("MainWindow", "REPORTS"))
        self.label_3.setText(_translate("MainWindow", "Time"))
        self.pushButton_10.setText(_translate("MainWindow", "DASHBOARD"))
        self.HOME.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">HOME</span></p></body></html>"))
        self.pushButton_8.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "Start working here!"))
        self.welcome.setText(_translate("MainWindow", "Welcome,"))
        self.khichle.setText(_translate("MainWindow", "Let\'s make today productive!"))
        self.label_5.setText(_translate("MainWindow", "Goal:"))
        self.increase.setText(_translate("MainWindow", "+12% last week"))
        self.goal.setText(_translate("MainWindow", "85%"))
        self.label_4.setText(_translate("MainWindow", "Weekly Performance"))
        self.label_7.setText(_translate("MainWindow", "Sara!"))
