# Form implementation generated from reading ui file 'C:\Users\legal\PycharmProjects\PythonProject\MainApp\UI\UI_LOGIN.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 512)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 10, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0px solid rgb(31, 92, 171);\n"
"color: rgb(31, 92, 171);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 461, 181))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 0px solid rgb(31, 92, 171);\n"
"color: rgb(31, 92, 171);")
        self.label_4.setObjectName("label_4")
        self.gridFrame_6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_6.setGeometry(QtCore.QRect(480, 80, 261, 291))
        self.gridFrame_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"border: 2px solid rgb(31, 92, 171);")
        self.gridFrame_6.setObjectName("gridFrame_6")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridFrame_6)
        self.lineEdit.setGeometry(QtCore.QRect(30, 150, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 0px;\n"
"border: 0px solid rgb(31, 92, 171);\n"
"background-color: rgb(234, 241, 251);")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.NoEcho)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_faceid = QtWidgets.QPushButton(parent=self.gridFrame_6)
        self.pushButton_faceid.setGeometry(QtCore.QRect(200, 150, 41, 31))
        self.pushButton_faceid.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 0px;\n"
"border-radius: 0px;\n"
"border: 0px solid rgb(31, 92, 171);")
        self.pushButton_faceid.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\legal\\PycharmProjects\\PythonProject\\MainApp\\UI\\../../../../../../Downloads/f99e9a15dc732f325c100c54af3e85dd.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_faceid.setIcon(icon)
        self.pushButton_faceid.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_faceid.setObjectName("pushButton_faceid")
        self.label_5 = QtWidgets.QLabel(parent=self.gridFrame_6)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 0px solid rgb(31, 92, 171);\n"
"color: rgb(31, 92, 171);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.gridFrame_6)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: 0px solid rgb(31, 92, 171);\n"
"color: rgb(31, 92, 171);")
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 800, 471))
        self.label_3.setStyleSheet("border: 2px solid rgb(31, 92, 171);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\legal\\PycharmProjects\\PythonProject\\MainApp\\UI\\../UI APP/background2.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.gridFrame_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600;\">PowerSight</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">The best to both enterprises and employees</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Your Employee ID"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Welcome!</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Log in to your Account</span></p></body></html>"))
