# Form implementation generated from reading ui file 'C:\Users\legal\PycharmProjects\PythonProject\MainApp\UI\UI_MG_EMPLIST.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 512)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(0, 0, 151, 51))
        self.gridFrame.setStyleSheet("background-color: rgb(30, 33, 40);")
        self.gridFrame.setObjectName("gridFrame")
        self.label = QtWidgets.QLabel(parent=self.gridFrame)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridFrame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_2.setGeometry(QtCore.QRect(0, 50, 151, 371))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gridFrame_2.setFont(font)
        self.gridFrame_2.setStyleSheet("background-color: rgb(47, 53, 58);")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center;\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 170, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center;\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 210, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center;\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 90, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center;\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridFrame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_3.setGeometry(QtCore.QRect(0, 420, 151, 51))
        self.gridFrame_3.setStyleSheet("background-color: rgb(30, 33, 40);")
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridFrame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_5.setGeometry(QtCore.QRect(150, 50, 651, 421))
        self.gridFrame_5.setStyleSheet("background-color: rgb(227, 244, 245);")
        self.gridFrame_5.setObjectName("gridFrame_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridFrame_5)
        self.lineEdit.setGeometry(QtCore.QRect(450, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.NoEcho)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.gridFrame_5)
        self.pushButton_15.setGeometry(QtCore.QRect(560, 70, 21, 21))
        self.pushButton_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.pushButton_15.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\legal\\PycharmProjects\\PythonProject\\MainApp\\UI\\../../../../../../Downloads/Screenshot 2025-12-12 232940.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setObjectName("pushButton_15")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.gridFrame_5)
        self.tableWidget.setGeometry(QtCore.QRect(70, 110, 511, 221))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(129)
        self.tableWidget.verticalHeader().setVisible(False)
        self.label_4 = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.label_4.setGeometry(QtCore.QRect(110, 70, 51, 20))
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(parent=self.gridFrame_5)
        self.comboBox.setGeometry(QtCore.QRect(180, 70, 61, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.label_5 = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.label_5.setGeometry(QtCore.QRect(250, 70, 71, 20))
        self.label_5.setObjectName("label_5")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.gridFrame_5)
        self.comboBox_2.setGeometry(QtCore.QRect(330, 70, 61, 22))
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 131, 41))
        self.label_2.setObjectName("label_2")
        self.gridFrame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_4.setGeometry(QtCore.QRect(150, 0, 651, 51))
        self.gridFrame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridFrame_4.setObjectName("gridFrame_4")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 21, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center; \n"
"hover {\n"
"    background-color: white; \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(420, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center; \n"
"hover {\n"
"    background-color: white; \n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center; \n"
"hover {\n"
"    background-color: white; \n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_10.setGeometry(QtCore.QRect(250, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_17.setGeometry(QtCore.QRect(220, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center; \n"
"hover {\n"
"    background-color: white; \n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">PowerSight</span></p></body></html>"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Notification"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Languages"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Help"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Account"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Employee ID"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Year:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Month:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">EMPLOYEE LIST</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "HOME"))
        self.pushButton_8.setText(_translate("MainWindow", "DASHBOARD"))
        self.pushButton_9.setText(_translate("MainWindow", "REPORTS"))
        self.pushButton_10.setText(_translate("MainWindow", "REPORTS"))
        self.pushButton_17.setText(_translate("MainWindow", "CHATBOT"))
