# Form implementation generated from reading ui file 'C:\Users\legal\PycharmProjects\PythonProject\MainApp\UI\UI_MG_HOME.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 559)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(0, 0, 151, 101))
        self.gridFrame.setStyleSheet("background-color: rgb(30, 33, 40);")
        self.gridFrame.setObjectName("gridFrame")
        self.label = QtWidgets.QLabel(parent=self.gridFrame)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridFrame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_2.setGeometry(QtCore.QRect(0, 50, 151, 371))
        self.gridFrame_2.setStyleSheet("background-color: rgb(47, 53, 58);")
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 90, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center;\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center;\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 170, 131, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center;\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.gridFrame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 210, 131, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center;\n"
"hover {\n"
"    background-color: #4A4D52; \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridFrame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_3.setGeometry(QtCore.QRect(0, 420, 151, 51))
        self.gridFrame_3.setStyleSheet("background-color: rgb(30, 33, 40);")
        self.gridFrame_3.setObjectName("gridFrame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridFrame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_5.setGeometry(QtCore.QRect(150, 50, 651, 421))
        self.gridFrame_5.setStyleSheet("background-color: rgb(227, 244, 245);")
        self.gridFrame_5.setObjectName("gridFrame_5")
        self.gridFrame_6 = QtWidgets.QFrame(parent=self.gridFrame_5)
        self.gridFrame_6.setGeometry(QtCore.QRect(20, 90, 291, 101))
        self.gridFrame_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(31, 92, 171);\n"
"border-radius: 10px;")
        self.gridFrame_6.setObjectName("gridFrame_6")
        self.label_6 = QtWidgets.QLabel(parent=self.gridFrame_6)
        self.label_6.setGeometry(QtCore.QRect(200, 10, 81, 81))
        self.label_6.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"border-radius: 0px;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\Users\\legal\\PycharmProjects\\PythonProject\\MainApp\\UI\\../../../../../../Downloads/4076fcfe75ac91635549cda45a12fe6a.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.helloName = QtWidgets.QLineEdit(parent=self.gridFrame_6)
        self.helloName.setGeometry(QtCore.QRect(10, 10, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.helloName.setFont(font)
        self.helloName.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(31, 92, 171);\n"
"border-radius: 0px;")
        self.helloName.setObjectName("helloName")
        self.label_7 = QtWidgets.QLabel(parent=self.gridFrame_6)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: 2px solid rgb(255, 255, 255);\n"
"color: rgb(31, 92, 171);\n"
"border-radius: 0px;\n"
"")
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.gridFrame_5)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.NoEcho)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(31, 92, 171);")
        self.label_4.setObjectName("label_4")
        self.listWidget = QtWidgets.QListWidget(parent=self.gridFrame_5)
        self.listWidget.setGeometry(QtCore.QRect(340, 60, 291, 341))
        self.listWidget.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(31, 92, 171);")
        self.listWidget.setObjectName("listWidget")
        self.label_5 = QtWidgets.QLabel(parent=self.gridFrame_5)
        self.label_5.setGeometry(QtCore.QRect(370, 70, 231, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 92, 171);")
        self.label_5.setObjectName("label_5")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.gridFrame_5)
        self.pushButton_10.setGeometry(QtCore.QRect(360, 120, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(31, 92, 171);\n"
"border-radius: 5px;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.gridFrame_5)
        self.pushButton_11.setGeometry(QtCore.QRect(360, 170, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(31, 92, 171);\n"
"border-radius: 5px;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.gridFrame_5)
        self.pushButton_12.setGeometry(QtCore.QRect(360, 220, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(31, 92, 171);\n"
"border-radius: 5px;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.gridFrame_5)
        self.pushButton_13.setGeometry(QtCore.QRect(360, 270, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(31, 92, 171);\n"
"border-radius: 5px;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.gridFrame_5)
        self.pushButton_14.setGeometry(QtCore.QRect(360, 320, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(31, 92, 171);\n"
"border-radius: 5px;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.gridFrame_5)
        self.pushButton_15.setGeometry(QtCore.QRect(290, 60, 21, 21))
        self.pushButton_15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.pushButton_15.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\legal\\PycharmProjects\\PythonProject\\MainApp\\UI\\../../../../../../Downloads/Screenshot 2025-12-12 232940.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setObjectName("pushButton_15")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.gridFrame_5)
        self.scrollArea.setGeometry(QtCore.QRect(20, 230, 291, 171))
        self.scrollArea.setStyleSheet("background-color: rgb(227, 244, 245);\n"
"border-radius: 10px;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 291, 171))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridFrame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.gridFrame_4.setGeometry(QtCore.QRect(150, 0, 651, 51))
        self.gridFrame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridFrame_4.setObjectName("gridFrame_4")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 21, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center; \n"
"hover {\n"
"    background-color: white; \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(440, 50, 56, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(420, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center; \n"
"hover {\n"
"    background-color: white; \n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center; \n"
"hover {\n"
"    background-color: white; \n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_16.setGeometry(QtCore.QRect(250, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.gridFrame_4)
        self.pushButton_17.setGeometry(QtCore.QRect(220, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("background-color: transparent; \n"
"border: none;\n"
"padding: 15px 0px 20px 5px; \n"
"text-align: center; \n"
"hover {\n"
"    background-color: white; \n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">PowerSight</span></p></body></html>"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Account"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Notification"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Languages"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Help"))
        self.helloName.setText(_translate("MainWindow", "Hello, Sarah!"))
        self.label_7.setText(_translate("MainWindow", "Wishing you a wonderfull workday. Let\'s get started!"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">HOME</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Recent</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Pending Feedback</span></p></body></html>"))
        self.pushButton_10.setText(_translate("MainWindow", "Alexander\'s Feedback"))
        self.pushButton_11.setText(_translate("MainWindow", "Anna\'s Feedback"))
        self.pushButton_12.setText(_translate("MainWindow", "Jessica\'s Feedback"))
        self.pushButton_13.setText(_translate("MainWindow", "John\'s Feedback"))
        self.pushButton_14.setText(_translate("MainWindow", "Hana\'s Feedback"))
        self.pushButton_6.setText(_translate("MainWindow", "HOME"))
        self.pushButton_7.setText(_translate("MainWindow", "HOME"))
        self.pushButton_8.setText(_translate("MainWindow", "DASHBOARD"))
        self.pushButton_9.setText(_translate("MainWindow", "REPORTS"))
        self.pushButton_16.setText(_translate("MainWindow", "REPORTS"))
        self.pushButton_17.setText(_translate("MainWindow", "CHATBOT"))
